-- Execute este SQL no Supabase: SQL Editor → New query → Cole e rode.
-- Cria a tabela fighters e libera leitura/inserção com a chave anon.

create table if not exists public.fighters (
  id bigint generated by default as identity primary key,
  name text not null,
  nick text,
  nationality text,
  division text,
  dob date,
  height_cm int,
  weight_kg int,
  team text,
  team_id bigint,
  wins int default 0,
  losses int default 0,
  draws int default 0,
  rank int,
  flag text,
  bio text,
  photo_url text,
  created_at timestamptz default now()
);

alter table public.fighters enable row level security;

create policy "Permitir leitura pública"
  on public.fighters for select
  using (true);

create policy "Permitir inserção pública"
  on public.fighters for insert
  with check (true);
