-- ============================================================
-- FightHub — Migração Completa do Banco de Dados
-- Execute no Supabase: SQL Editor → New query → Cole e rode.
-- ============================================================

-- ============================================================
-- 1. TABELA: teams
-- ============================================================
create table if not exists public.teams (
  id bigint generated by default as identity primary key,
  name text not null,
  location text,
  emoji text default '🥊',
  coach text,
  founded text,
  meta text,
  fighters_count int default 0,
  wins_count int default 0,
  titles_count int default 0,
  created_at timestamptz default now()
);

alter table public.teams enable row level security;

create policy "teams_select" on public.teams for select using (true);
create policy "teams_insert" on public.teams for insert with check (true);
create policy "teams_update" on public.teams for update using (true);
create policy "teams_delete" on public.teams for delete using (true);

-- ============================================================
-- 2. TABELA: fighters (recria se já existir, para garantir estrutura)
-- ============================================================
-- Dropar policies existentes se houver
do $$
begin
  drop policy if exists "Permitir leitura pública" on public.fighters;
  drop policy if exists "Permitir inserção pública" on public.fighters;
exception when others then null;
end $$;

drop table if exists public.fighters cascade;

create table public.fighters (
  id bigint generated by default as identity primary key,
  name text not null,
  nick text,
  nationality text,
  division text,
  dob date,
  height_cm int,
  weight_kg int,
  team text,
  team_id bigint references public.teams(id) on delete set null,
  wins int default 0,
  losses int default 0,
  draws int default 0,
  rank int,
  flag text default '🇧🇷',
  bio text,
  photo_url text,
  created_at timestamptz default now()
);

alter table public.fighters enable row level security;

create policy "fighters_select" on public.fighters for select using (true);
create policy "fighters_insert" on public.fighters for insert with check (true);
create policy "fighters_update" on public.fighters for update using (true);
create policy "fighters_delete" on public.fighters for delete using (true);

-- ============================================================
-- 3. TABELA: events
-- ============================================================
create table if not exists public.events (
  id bigint generated by default as identity primary key,
  name text not null,
  organization text,
  event_date date not null,
  city text,
  status text default 'upcoming' check (status in ('upcoming', 'past', 'live')),
  fights_count int default 8,
  created_at timestamptz default now()
);

alter table public.events enable row level security;

create policy "events_select" on public.events for select using (true);
create policy "events_insert" on public.events for insert with check (true);
create policy "events_update" on public.events for update using (true);
create policy "events_delete" on public.events for delete using (true);

-- ============================================================
-- 4. TABELA: fights (histórico de lutas)
-- ============================================================
create table if not exists public.fights (
  id bigint generated by default as identity primary key,
  fighter_id bigint references public.fighters(id) on delete cascade,
  opponent_name text not null,
  result text check (result in ('W', 'L', 'D')),
  method text,
  event_name text,
  fight_date text,
  round_info text,
  created_at timestamptz default now()
);

alter table public.fights enable row level security;

create policy "fights_select" on public.fights for select using (true);
create policy "fights_insert" on public.fights for insert with check (true);
create policy "fights_update" on public.fights for update using (true);
create policy "fights_delete" on public.fights for delete using (true);

-- ============================================================
-- 5. TABELA: rankings
-- ============================================================
create table if not exists public.rankings (
  id bigint generated by default as identity primary key,
  fighter_name text not null,
  team text,
  country text,
  weight_class text not null,
  wins int default 0,
  losses int default 0,
  last_result text check (last_result in ('W', 'L')),
  position int default 0,
  fighter_id bigint references public.fighters(id) on delete set null,
  created_at timestamptz default now()
);

alter table public.rankings enable row level security;

create policy "rankings_select" on public.rankings for select using (true);
create policy "rankings_insert" on public.rankings for insert with check (true);
create policy "rankings_update" on public.rankings for update using (true);
create policy "rankings_delete" on public.rankings for delete using (true);

-- ============================================================
-- 6. SEED DATA — Equipes
-- ============================================================
insert into public.teams (id, name, location, emoji, coach, founded, meta, fighters_count, wins_count, titles_count) values
  (1, 'Pitbull Brothers', 'Brasília, DF', '🐾', 'Roberto Nunes', '2010', 'Academia especializada em Kickboxing e Muay Thai', 12, 87, 5),
  (2, 'Chute Boxe Academy', 'Curitiba, PR', '🥊', 'Diego Lima', '2005', 'Uma das mais tradicionais academias de artes marciais do Brasil', 24, 142, 11),
  (3, 'Predadores Team', 'São Paulo, SP', '🐆', 'Carlos Mendes', '2012', 'Formando campeões nacionais e internacionais', 18, 98, 7),
  (4, 'Dragão Team', 'Rio de Janeiro, RJ', '🐉', 'Paulo Dragon', '2008', 'Tradição e excelência no kickboxing carioca', 15, 76, 4),
  (5, 'Iron Fist Academy', 'Belo Horizonte, MG', '👊', 'Fábio Iron', '2015', 'Especialistas no desenvolvimento de atletas femininas e masculinas', 9, 54, 3)
on conflict (id) do nothing;

-- Reset sequence
select setval('teams_id_seq', (select coalesce(max(id), 0) from public.teams));

-- ============================================================
-- 7. SEED DATA — Lutadores
-- ============================================================
insert into public.fighters (id, name, nick, nationality, division, dob, height_cm, weight_kg, team, team_id, wins, losses, draws, rank, flag, bio) values
  (1, 'Rafael Fiziev', '"Ataman"', '🇰🇿 Cazaquistão', 'Peso Leve (−65kg)', '1992-04-05', 175, 65, 'Pitbull Brothers', 1, 11, 2, 0, 1, '🇰🇿', 'Rafael Fiziev é um dos kickboxers mais explosivos da sua geração, conhecido por seus knockouts devastadores e movimentação ofensiva imprevisível.'),
  (2, 'Bruno Machado', '"The Machine"', '🇧🇷 Brasil', 'Peso Leve (−65kg)', '1994-08-22', 172, 64, 'Chute Boxe Academy', 2, 18, 3, 1, 2, '🇧🇷', 'Bruno Machado é uma das maiores promessas do kickboxing brasileiro. Conhecido pelo volume de golpes e resistência física extraordinária.'),
  (3, 'Caio Borralho', '"The Natural"', '🇧🇷 Brasil', 'Peso Médio (−75kg)', '1995-03-10', 183, 75, 'Predadores Team', 3, 14, 1, 0, 1, '🇧🇷', 'Caio Borralho domina o peso médio com uma combinação devastadora de velocidade e potência técnica.'),
  (4, 'Marcus Santos', '"Iron Fist"', '🇧🇷 Brasil', 'Peso Pesado (+81kg)', '1990-11-15', 190, 92, 'Dragão Team', 4, 22, 5, 2, 3, '🇧🇷', 'Veterano do kickboxing nacional, Marcus Santos é reconhecido pela força explosiva e longa experiência em grandes palcos.'),
  (5, 'Ana Lima', '"The Warrior"', '🇧🇷 Brasil', 'Peso Galo (−56kg)', '1997-06-30', 162, 55, 'Iron Fist Academy', 5, 9, 2, 0, 1, '🇧🇷', 'Ana Lima é a principal lutadora feminina do kickboxing brasileiro, com três títulos nacionais.'),
  (6, 'Diego Ferreira', '"The Dragon"', '🇧🇷 Brasil', 'Peso Meio-Médio (−71kg)', '1993-02-18', 178, 70, 'Chute Boxe Academy', 2, 15, 4, 1, 2, '🇧🇷', 'Diego Ferreira é um técnico completo que mistura potência e inteligência dentro do ringue.')
on conflict (id) do nothing;

select setval('fighters_id_seq', (select coalesce(max(id), 0) from public.fighters));

-- ============================================================
-- 8. SEED DATA — Eventos
-- ============================================================
insert into public.events (id, name, organization, event_date, city, status, fights_count) values
  (1, 'FightHub Grand Prix 2025', 'FightHub', '2025-03-15', 'São Paulo, SP', 'upcoming', 10),
  (2, 'Brazilian Kickboxing Championship', 'CBKB', '2025-02-28', 'Rio de Janeiro, RJ', 'upcoming', 8),
  (3, 'Copa Sul de Kickboxing', 'FKRS', '2025-04-20', 'Porto Alegre, RS', 'upcoming', 12),
  (4, 'SP Open Kickboxing', 'FKESP', '2024-12-10', 'São Paulo, SP', 'past', 14),
  (5, 'Rio Fight Night', 'RFN Promotions', '2024-11-22', 'Rio de Janeiro, RJ', 'past', 9),
  (6, 'Grand Slam Kickboxing', 'CBKB', '2024-10-05', 'Belo Horizonte, MG', 'past', 11)
on conflict (id) do nothing;

select setval('events_id_seq', (select coalesce(max(id), 0) from public.events));

-- ============================================================
-- 9. SEED DATA — Histórico de Lutas
-- ============================================================
insert into public.fights (fighter_id, opponent_name, result, method, event_name, fight_date, round_info) values
  -- Rafael Fiziev (id=1)
  (1, 'Luis Torres', 'W', 'KO (Chute Circular)', 'GP Kickboxing 2024', 'Nov 2024', 'R2 1:23'),
  (1, 'Carlos Smith', 'W', 'Dec. Unânime', 'Copa Brasil 2024', 'Set 2024', '3R'),
  (1, 'Ivan Volkov', 'L', 'KO (Direto)', 'World Clash 2023', 'Jun 2023', 'R1 2:45'),
  (1, 'Bruno Costa', 'W', 'TKO (Chutes)', 'SP Open 2023', 'Mar 2023', 'R3'),
  (1, 'Marcos Tavares', 'W', 'Dec. Unânime', 'Copa BR 2022', 'Dez 2022', '3R'),
  -- Bruno Machado (id=2)
  (2, 'Felipe Neto', 'W', 'TKO (Joelhada)', 'FightHub GP 2024', 'Dez 2024', 'R2 2:10'),
  (2, 'Paulo Araújo', 'W', 'Dec. Dividida', 'Copa BR 2024', 'Out 2024', '3R'),
  (2, 'Ricardo Melo', 'W', 'KO (Combinação)', 'SP Open 2024', 'Jul 2024', 'R1 0:58'),
  (2, 'Rafael Fiziev', 'L', 'Dec. Unânime', 'Grand Slam 2023', 'Out 2023', '3R'),
  -- Caio Borralho (id=3)
  (3, 'Fernando Costa', 'W', 'KO (Cruzado)', 'Copa SP 2024', 'Nov 2024', 'R1 1:45'),
  (3, 'Alexei Nikitin', 'W', 'Dec. Unânime', 'World Cup 2024', 'Ago 2024', '3R'),
  (3, 'Pedro Alves', 'W', 'TKO (Combinação)', 'GP Brasil 2024', 'Mai 2024', 'R2 2:30'),
  -- Marcus Santos (id=4)
  (4, 'Roberto Biggão', 'W', 'KO (Direto)', 'RJ Fight Night 2024', 'Out 2024', 'R1 0:45'),
  (4, 'Artem Vovchanchyn', 'L', 'Dec. Dividida', 'International Open 2024', 'Jul 2024', '3R'),
  (4, 'Lucas Brito', 'W', 'TKO (Sequência)', 'Copa BR 2024', 'Abr 2024', 'R3 1:10'),
  -- Ana Lima (id=5)
  (5, 'Sofia Mendez', 'W', 'Dec. Unânime', 'Copa Feminina 2024', 'Nov 2024', '3R'),
  (5, 'Keiko Tanaka', 'W', 'TKO (Chutes)', 'World Women 2024', 'Ago 2024', 'R2 2:55'),
  (5, 'Maria Oliveira', 'L', 'Dec. Dividida', 'GP Feminino 2023', 'Mai 2023', '3R'),
  -- Diego Ferreira (id=6)
  (6, 'Marcus Almeida', 'W', 'KO (Contra-ataque)', 'Copa Sul 2024', 'Out 2024', 'R2 1:50'),
  (6, 'Kiro Tanaka', 'W', 'Dec. Unânime', 'International Cup 2024', 'Jul 2024', '3R'),
  (6, 'Pedro Santos', 'L', 'TKO (Cortes)', 'GP SP 2024', 'Mar 2024', 'R3 2:20');

-- ============================================================
-- 10. SEED DATA — Rankings
-- ============================================================
insert into public.rankings (fighter_name, team, country, weight_class, wins, losses, last_result, position) values
  -- Peso Pena (−60kg)
  ('João Victor', 'Pitbull Brothers', '🇧🇷 Brasil', 'Peso Pena (−60kg)', 16, 1, 'W', 1),
  ('Carlos Moura', 'SP Fight', '🇧🇷 Brasil', 'Peso Pena (−60kg)', 12, 3, 'W', 2),
  ('Pierre Dubois', 'French KB', '🇫🇷 França', 'Peso Pena (−60kg)', 14, 4, 'L', 3),
  ('Tanapon Jitmuan', 'Thailand Elite', '🇹🇭 Tailândia', 'Peso Pena (−60kg)', 18, 5, 'W', 4),
  ('Diego Santos', 'Dragão Team', '🇧🇷 Brasil', 'Peso Pena (−60kg)', 10, 2, 'W', 5),
  -- Peso Leve (−65kg)
  ('Rafael Fiziev', 'Pitbull Brothers', '🇰🇿 Cazaquistão', 'Peso Leve (−65kg)', 11, 2, 'W', 1),
  ('Bruno Machado', 'Chute Boxe Academy', '🇧🇷 Brasil', 'Peso Leve (−65kg)', 18, 3, 'W', 2),
  ('Jamal Hassan', 'Dutch School', '🇳🇱 Holanda', 'Peso Leve (−65kg)', 15, 4, 'W', 3),
  ('Pedro Alves', 'Predadores', '🇧🇷 Brasil', 'Peso Leve (−65kg)', 9, 2, 'L', 4),
  ('Michael Chen', 'USA Kickboxing', '🇺🇸 EUA', 'Peso Leve (−65kg)', 11, 3, 'W', 5),
  -- Peso Médio (−75kg)
  ('Caio Borralho', 'Predadores Team', '🇧🇷 Brasil', 'Peso Médio (−75kg)', 14, 1, 'W', 1),
  ('Alexei Nikitin', 'Russian Top Team', '🇷🇺 Rússia', 'Peso Médio (−75kg)', 17, 3, 'W', 2),
  ('Fernando Costa', 'Chute Boxe', '🇧🇷 Brasil', 'Peso Médio (−75kg)', 12, 5, 'L', 3),
  ('Ahmed Al-Rashid', 'Dubai KB', '🇦🇪 EAU', 'Peso Médio (−75kg)', 10, 2, 'W', 4),
  -- Peso Meio-Médio (−71kg)
  ('Diego Ferreira', 'Chute Boxe Academy', '🇧🇷 Brasil', 'Peso Meio-Médio (−71kg)', 15, 4, 'W', 1),
  ('Marcus Almeida', 'Team SP', '🇧🇷 Brasil', 'Peso Meio-Médio (−71kg)', 13, 2, 'W', 2),
  ('Kiro Tanaka', 'Japan Elite', '🇯🇵 Japão', 'Peso Meio-Médio (−71kg)', 12, 3, 'L', 3),
  -- Peso Pesado (+81kg)
  ('Marcus Santos', 'Dragão Team', '🇧🇷 Brasil', 'Peso Pesado (+81kg)', 22, 5, 'W', 1),
  ('Artem Vovchanchyn', 'UA Strong', '🇺🇦 Ucrânia', 'Peso Pesado (+81kg)', 19, 4, 'W', 2),
  ('Roberto Biggão', 'RJ Fight', '🇧🇷 Brasil', 'Peso Pesado (+81kg)', 14, 8, 'W', 3),
  -- Peso Galo (−56kg)
  ('Ana Lima', 'Iron Fist Academy', '🇧🇷 Brasil', 'Peso Galo (−56kg)', 9, 2, 'W', 1),
  ('Keiko Tanaka', 'Japan Kick', '🇯🇵 Japão', 'Peso Galo (−56kg)', 11, 3, 'W', 2),
  ('Sofia Mendez', 'Arg KB', '🇦🇷 Argentina', 'Peso Galo (−56kg)', 8, 2, 'L', 3),
  -- Peso Meio-Pesado (−81kg)
  ('Lucas Brito', 'SP Power', '🇧🇷 Brasil', 'Peso Meio-Pesado (−81kg)', 13, 2, 'W', 1),
  ('Dmitri Volkov', 'Russia KB', '🇷🇺 Rússia', 'Peso Meio-Pesado (−81kg)', 15, 4, 'W', 2),
  ('Felipe Guerra', 'Predadores', '🇧🇷 Brasil', 'Peso Meio-Pesado (−81kg)', 10, 3, 'W', 3),
  -- Peso Mosca (−52kg)
  ('Rafinha Speed', 'BH Kicks', '🇧🇷 Brasil', 'Peso Mosca (−52kg)', 12, 1, 'W', 1),
  ('Leo Ágil', 'Curitiba KB', '🇧🇷 Brasil', 'Peso Mosca (−52kg)', 10, 2, 'W', 2),
  ('Chang Wei', 'China Elite', '🇨🇳 China', 'Peso Mosca (−52kg)', 14, 3, 'L', 3);

-- ============================================================
-- DONE! Todas as tabelas criadas e populadas.
-- ============================================================
